Motax/Models/DealerDetail.cs
using System;
using System.Collections.Generic;

namespace Motax.Models;

public partial class DealerDetail
{
    public int Id { get; set; }

    public int DealerId { get; set; }

    public string? CoverImage { get; set; }

    public string? AvatarImage { get; set; }

    public string? ConsultantName { get; set; }

    public string? ConsultantAvatar { get; set; }

    public virtual Dealer Dealer { get; set; } = null!;
}

Motax/Areas/Admin/Controllers/DealerDetailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Motax.Models;
using Motax.ViewModels;
using System.IO;
using System.Threading.Tasks;

namespace Motax.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/DealerDetail")]
    [Authorize(Policy = "CheckAdmin")]
    public class DealerDetailController : Controller
    {
        private readonly MotaxContext db;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DealerDetailController(MotaxContext context, IWebHostEnvironment hc)
        {
            db = context;
            webHostEnvironment = hc;
        }

        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            return View(await db.DealerDetails.OrderByDescending(b => b.Id).ToListAsync());
        }

        #region Create
        [Route("Create")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.dealers = new SelectList(db.Dealers, "Id", "Name");
            return View();
        }

        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DealerDetailAdminVM dd)
        {
            if (ModelState.IsValid)
            {
                string coverImageFilename = "", avatarImageFilename = "", consultantAvatarFilename = "";

                if (dd.CoverImage != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Cover");
                    coverImageFilename = Guid.NewGuid().ToString() + "_" + dd.CoverImage.FileName;
                    string filePath = Path.Combine(uploadFolder, coverImageFilename);
                    dd.CoverImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                if (dd.AvatarImage != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Avatar");
                    avatarImageFilename = Guid.NewGuid().ToString() + "_" + dd.AvatarImage.FileName;
                    string filePath = Path.Combine(uploadFolder, avatarImageFilename);
                    dd.AvatarImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                if (dd.ConsultantAvatar != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Consultant");
                    consultantAvatarFilename = Guid.NewGuid().ToString() + "_" + dd.ConsultantAvatar.FileName;
                    string filePath = Path.Combine(uploadFolder, consultantAvatarFilename);
                    dd.ConsultantAvatar.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                DealerDetail dealerDetail = new DealerDetail()
                {
                    DealerId = dd.DealerId,
                    CoverImage = coverImageFilename,
                    AvatarImage = avatarImageFilename,
                    ConsultantName = dd.ConsultantName,
                    ConsultantAvatar = consultantAvatarFilename
                };

                db.DealerDetails.Add(dealerDetail);
                await db.SaveChangesAsync();
                TempData["success"] = "Create success dealer detail!";
                return RedirectToAction("Index");
            }

            return View(dd);
        }
        #endregion

        #region Edit
        [Route("Edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            DealerDetail? dd = await db.DealerDetails.FindAsync(Id);
            if (dd == null)
            {
                return RedirectToAction("/404");
            }

            DealerDetailAdminVM vm = new DealerDetailAdminVM
            {
                Id = dd.Id,
                DealerId = dd.DealerId,
                ConsultantName = dd.ConsultantName,
                ExistingCoverImage = dd.CoverImage,
                ExistingAvatarImage = dd.AvatarImage,
                ExistingConsultantAvatar = dd.ConsultantAvatar
            };

            ViewBag.dealers = new SelectList(db.Dealers, "Id", "Name");
            return View(vm);
        }

        [Route("Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DealerDetailAdminVM dd)
        {
            if (ModelState.IsValid)
            {
                var dealerDetailToUpdate = await db.DealerDetails.FindAsync(dd.Id);
                if (dealerDetailToUpdate == null)
                {
                    return NotFound();
                }

                if (dd.CoverImage != null)
                {
                    if (!string.IsNullOrEmpty(dealerDetailToUpdate.CoverImage))
                    {
                        string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Cover", dealerDetailToUpdate.CoverImage);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Cover");
                    string filename = Guid.NewGuid().ToString() + "_" + dd.CoverImage.FileName;
                    string filePath = Path.Combine(uploadFolder, filename);
                    dd.CoverImage.CopyTo(new FileStream(filePath, FileMode.Create));
                    dealerDetailToUpdate.CoverImage = filename;
                }

                if (dd.AvatarImage != null)
                {
                    if (!string.IsNullOrEmpty(dealerDetailToUpdate.AvatarImage))
                    {
                        string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Avatar", dealerDetailToUpdate.AvatarImage);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Avatar");
                    string filename = Guid.NewGuid().ToString() + "_" + dd.AvatarImage.FileName;
                    string filePath = Path.Combine(uploadFolder, filename);
                    dd.AvatarImage.CopyTo(new FileStream(filePath, FileMode.Create));
                    dealerDetailToUpdate.AvatarImage = filename;
                }

                if (dd.ConsultantAvatar != null)
                {
                    if (!string.IsNullOrEmpty(dealerDetailToUpdate.ConsultantAvatar))
                    {
                        string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Consultant", dealerDetailToUpdate.ConsultantAvatar);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Consultant");
                    string filename = Guid.NewGuid().ToString() + "_" + dd.ConsultantAvatar.FileName;
                    string filePath = Path.Combine(uploadFolder, filename);
                    dd.ConsultantAvatar.CopyTo(new FileStream(filePath, FileMode.Create));
                    dealerDetailToUpdate.ConsultantAvatar = filename;
                }

                dealerDetailToUpdate.DealerId = dd.DealerId;
                dealerDetailToUpdate.ConsultantName = dd.ConsultantName;

                db.Update(dealerDetailToUpdate);
                await db.SaveChangesAsync();
                TempData["success"] = "Dealer detail updated successfully!";
                return RedirectToAction("Index");
            }

            return View(dd);
        }
        #endregion

        #region Delete
        [Route("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var dealerDetailToDelete = await db.DealerDetails.FindAsync(Id);
            if (dealerDetailToDelete == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrEmpty(dealerDetailToDelete.CoverImage))
            {
                string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Cover", dealerDetailToDelete.CoverImage);
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            if (!string.IsNullOrEmpty(dealerDetailToDelete.AvatarImage))
            {
                string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Avatar", dealerDetailToDelete.AvatarImage);
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            if (!string.IsNullOrEmpty(dealerDetailToDelete.ConsultantAvatar))
            {
                string oldImagePath = Path.Combine(webHostEnvironment.WebRootPath, "Images/Dealers/DealerDetail/Consultant", dealerDetailToDelete.ConsultantAvatar);
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            db.DealerDetails.Remove(dealerDetailToDelete);
            await db.SaveChangesAsync();

Motax/Areas/Admin/Views/DealerDetail/Create.cshtml
@model Motax.ViewModels.DealerDetailAdminVM
@{
    ViewData["Title"] = "Create DealerDetail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutBackend.cshtml";
}

<div class="col-xl-12" style="margin-top:20px;">
    <div class="card custom-card">
        <div class="card-header justify-content-between">
            <div class="card-title">
                Create Dealer Detail
            </div>
        </div>

        <div class="card-body" style="margin:10px;">
            <form asp-action="Create" asp-controller="DealerDetail" class="row g-3 mt-0" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="col-md-6">
                    <select asp-for="DealerId" class="form-control" asp-items="ViewBag.dealers">
                        <option value="0">--Choose a Dealer--</option>
                    </select>
                    <span asp-validation-for="DealerId" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="CoverImage" class="form-label">Cover Image</label>
                    <input asp-for="CoverImage" class="form-control" type="file">
                    <span asp-validation-for="CoverImage" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <label for="AvatarImage" class="form-label">Avatar Image</label>
                    <input asp-for="AvatarImage" class="form-control" type="file">
                    <span asp-validation-for="AvatarImage" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label class="form-label">Consultant Name</label>
                    <input asp-for="ConsultantName" class="form-control">
                    <span asp-validation-for="ConsultantName" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="ConsultantAvatar" class="form-label">Consultant Avatar</label>
                    <input asp-for="ConsultantAvatar" class="form-control" type="file">
                    <span asp-validation-for="ConsultantAvatar" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
            <a class="btn" style="color:blue; margin-top:5px;" asp-action="Index" asp-controller="DealerDetail">Back to list Dealer Details</a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Motax/Areas/Admin/Views/DealerDetail/Edit.cshtml
@model Motax.ViewModels.DealerDetailAdminVM
@{
    ViewData["Title"] = "Edit DealerDetail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutBackend.cshtml";
}

<div class="col-xl-12" style="margin-top:20px;">
    <div class="card custom-card">
        <div class="card-header justify-content-between">
            <div class="card-title">
                Edit Dealer Detail
            </div>
        </div>

        <div class="card-body" style="margin:10px;">
            <form asp-action="Edit" asp-controller="DealerDetail" class="row g-3 mt-0" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input type="hidden" asp-for="Id" />

                <div class="col-md-6">
                    <select asp-for="DealerId" class="form-control" asp-items="ViewBag.dealers">
                        <option value="0">--Choose a Dealer--</option>
                    </select>
                    <span asp-validation-for="DealerId" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="CoverImage" class="form-label">Cover Image</label>
                    <input asp-for="CoverImage" class="form-control" type="file">
                    <span asp-validation-for="CoverImage" class="text-danger"></span>
                    <img src="~/Images/DealerDetail/Cover/@Model.ExistingCoverImage" width="120px" height="120px" />
                </div>

                <div class="col-md-6">
                    <label for="AvatarImage" class="form-label">Avatar Image</label>
                    <input asp-for="AvatarImage" class="form-control" type="file">
                    <span asp-validation-for="AvatarImage" class="text-danger"></span>
                    <img src="~/Images/DealerDetail/Avatar/@Model.ExistingAvatarImage" width="120px" height="120px" />
                </div>

                <div class="col-md-6">
                    <label class="form-label">Consultant Name</label>
                    <input asp-for="ConsultantName" class="form-control">
                    <span asp-validation-for="ConsultantName" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="ConsultantAvatar" class="form-label">Consultant Avatar</label>
                    <input asp-for="ConsultantAvatar" class="form-control" type="file">
                    <span asp-validation-for="ConsultantAvatar" class="text-danger"></span>
                    <img src="~/Images/DealerDetail/Consultant/@Model.ExistingConsultantAvatar" width="120px" height="120px" />
                </div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
            <a class="btn" style="color:blue; margin-top:5px;" asp-action="Index" asp-controller="DealerDetail">Back to list Dealer Details</a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Motax/Areas/Admin/Views/DealerDetail/Index.cshtml
@model IEnumerable<DealerDetail>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutBackend.cshtml";
}

<div class="row">
    <div class="col-xl-12">
        <div class="card custom-card">
            <div class="card-header">
                <div class="card-title">List Dealer Detail </div> -------
                <div class="card-title">
                    <a class="btn btn-success label-btn" asp-action="Create" asp-controller="DealerDetail"> <i class="ri-chat-smile-line label-btn-icon me-2"></i> Add Dealer Detail</a>
                </div>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table id="file-export" class="table table-bordered text-nowrap w-100">
                        <thead>
                            <tr>
                                <th>Image Cover</th>
                                <th>Image Avatar</th>
                                <th>Consultant Name</th>
                                <th>Consultant Avatar</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="~/Images/Dealers/DealerDetail/Cover/@item.CoverImage" width="200px" height="120px" />
                                    </td>
                                    <td>
                                        <img src="~/Images/Dealers/DealerDetail/Avatar/@item.AvatarImage" width="120px" height="120px" />
                                    </td>
                                    <td>@item.ConsultantName</td>
                                    <td>
                                        <img src="~/Images/Dealers/DealerDetail/Consultant/@item.ConsultantAvatar" width="120px" height="120px" />
                                    </td>
                                    
                                    <td>
                                        <a class="btn btn-icon btn-sm btn-info-transparent rounded-pill" asp-action="Edit" asp-controller="DealerDetail" asp-route-id="@item.Id"> <i class="ri-edit-line"></i> </a>

                                        <form asp-action="Delete" asp-controller="DealerDetail" asp-route-id="@item.Id" method="post" style="display:inline;">
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="btn btn-icon btn-sm btn-danger-transparent rounded-pill" onclick="return confirm('Are you sure you want to delete this dealerDetail?');">
                                                <i class="ri-delete-bin-line"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>